/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2020-01-13 13:17:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_005fone_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/校淘二货/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/nm/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098682292000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1575818953231L));
    _jspx_dependants.put("jar:file:/D:/校淘二货/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/nm/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682292000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" id=\"style-css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/style.css\" type=\"text/css\" media=\"all\"> \r\n");
      out.write("<link rel=\"stylesheet\" id=\"fancybox-css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/jquery.fancybox.1.3.23.min.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header id=\"header\" class=\"header\" style=\"bacgroup-color:#00a67c;\">\r\n");
      out.write("\t  \r\n");
      out.write("\t\t<div class=\"container-inner\">\r\n");
      out.write("\t\t\t<div class=\"g-logo pull-center\">\r\n");
      out.write("\t\t\t\t<a target=\"_parent\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/MainController\">\r\n");
      out.write("\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"g-mono\" style=\"font-family:楷体;\">私人影院</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"g-bloger\" style=\"font-family:楷体;\">免费视频资源分享</span>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"search \" style=\"width:260px;display:block;position:absolute;bottom:0;right:87px;\">\r\n");
      out.write("\t\t\t\t\t<form target=\"_parent\" method=\"get\"  style=\"height:40px\" class=\"searchform themeform\"  action=\"QueryServlet\">\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\"  class=\"search\" name=\"s\"  placeholder=\"输入内容并回车\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"nav-header\" class=\"navbar\" style=\"border-bottom: 4px solid #00a67c ;\">\r\n");
      out.write("\t\t\t<style type=\"text/css\">.bdsharebuttonbox a{cursor:pointer;border-bottom:0;margin-right:5px;width:28px;height:28px;line-height:28px;color:#fff}.bds_renren{background:#94b3eb}.bds_qzone{background:#fac33f}.bds_more{background:#40a57d}.bds_weixin{background:#7ad071}.bdsharebuttonbox a:hover{background-color:#7fb4ab;color:#fff;border-bottom:0}</style>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul class=\"nav\">\r\n");
      out.write("\t\t\t\t<li id=\"menu-item-15\" class=\"menu-item menu-item-tpye-custom menu-itme-object-custom  current_page_item menu-item-home menu-itme-15\">\r\n");
      out.write("\t\t\t\t\t<a target=\"_parent\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/MainController\"><i class=\"fa fa-home\"></i>首页</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li id=\"menu-item-10\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-10\">\r\n");
      out.write("\t\t\t\t\t<a target=\"_parent\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/MenuServlet1\"><i class=\"fa fa-html5\"></i>电影</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li id=\"menu-item-7\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-7\">\r\n");
      out.write("\t\t\t\t\t<a target=\"_parent\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/MenuServlet2\"><i class=\"fa fa-cogs\"></i>电视剧</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li id=\"menu-item-9\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-9\">\r\n");
      out.write("\t\t\t\t\t<a target=\"_parent\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/MenuServlet3\"><i class=\"fa fa-firefox\"></i>动漫</a>\r\n");
      out.write("\t\t\t\t\t<!-- <ul class=\"sub-menu\"> \r\n");
      out.write("\t\t\t\t\t\t<li id=\"menu-item-11541\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-11541\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/\">棋牌源码</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"menu-item-782\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-782\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/\">游戏源码</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"menu-item-781\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-781\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/\">教程工具</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul> -->\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li id=\"menu-item-11\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-11\">\r\n");
      out.write("\t\t\t\t\t<a target=\"_parent\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/MenuServlet4\"><i class=\"fa fa-flag\"></i>综艺</a>\r\n");
      out.write("\t\t\t\t\t<!-- <ul class=\"sub-menu\"> \r\n");
      out.write("\t\t\t\t\t\t<li id=\"menu-item-786\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-786\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/\">英文程序</a>\r\n");
      out.write("\t\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t\t\t<li id=\"menu-item-783\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-783\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/\">英文工具</a>\r\n");
      out.write("\t\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t\t\t<li id=\"menu-item-785\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-785\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/\">英文模板</a>\r\n");
      out.write("\t\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t\t\t<li id=\"menu-item-784\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-784\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/\">英文数据</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul> -->\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li id=\"menu-item-8\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-8\">\r\n");
      out.write("\t\t\t\t\t<a target=\"_parent\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/MenuServlet5\"><i class=\"fa fa-users\"></i>用户上传</a>\r\n");
      out.write("\t\t\t\t\t<!-- <ul class=\"sub-menu\"> \r\n");
      out.write("\t\t\t\t\t\t<li id=\"menu-item-769\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-769\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/\">wordpress</a>\r\n");
      out.write("\t\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t\t\t<li id=\"menu-item-764\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-764\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/\">dedecms</a>\r\n");
      out.write("\t\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t\t\t<li id=\"menu-item-766\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-766\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">Discuz</a>\r\n");
      out.write("\t\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t\t\t<li id=\"menu-item-767\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-767\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">ECshop</a>\r\n");
      out.write("\t\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t\t\t<li id=\"menu-item-770\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-770\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">其他</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul> -->\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t <li id=\"menu-item-6\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-6\">\r\n");
      out.write("\t\t\t\t\t<a target=\"_parent\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/CommunicationController\"><i class=\"fa fa-comments-o\"></i>交流区</a>\r\n");
      out.write("\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t <!-- <li id=\"menu-item-5\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-5\">\r\n");
      out.write("\t\t\t\t\t<a target=\"_parent\" href=\"UploadController\"><i class=\"fa fa-user\"></i>用户上传</a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t\t<li id=\"menu-item-5\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-5\" style=\"margin-left:335.5px\">\r\n");
      out.write("\t\t\t\t\t\t<a target=\"_parent\" href=\"UploadController\"><i class=\"fa fa-user\"></i>上传视频</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<li id=\"menu-item-16\" style=\"float:right;\" class=\"menu-item menu-item-tpye-custom menu-itme-object-custom current-menu-item current_page_item menu-item-home menu-itme-16\" >\r\n");
      out.write("\t\t\t\t\t\t<a target=\"_parent\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp\"><i class=\"fa fa-upload\"></i>登录</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
